### ISSUE TITLE
Generate Files

### ISSUE THREAD

**Issue by emarsh25** [wentaoveggiebird/Siamese-MoNet#13]
I am trying to use the procedures and scripts to create the .mol2, .pops, and .profile files, but it appears the separate_pdb_chains.py does not seem to actually separate the chains as it should. It is potential I am just using it wrong, but I can not get it to seperate the pdb files into chains as it appears this script should do.

**Comment by emarsh25** [comment]
Additionally, step 3 does not work at all. I am not sure when I was supposed to install POPScomp or use their server, but that step is not clear at all on how to generate the pops file

**Comment by shiwentao00** [comment]
Resolved by this PR: https://github.com/shiwentao00/Graphsite-classifier/pull/18
